### ISSUE TITLE
Switch CC-BY-ND to CC-BY-SA

### ISSUE THREAD

**Issue by ghost** [agentyzmin/kyiv-transport-icons#2]
> Безкоштовно. З ~~вільною ліцензією~~.

`CC-BY-ND` is NOT **libre** license (as it prevent any reuse or modification, except personal-only usage)

Instead switch to `CC-BY-SA` — truly **libre** license.

**Comment by MrPaschenko** [comment]
I support the change, as I would like to upload the files under CC BY-ND license to Wikimedia, but it is unfortunately [prohibited](https://commons.wikimedia.org/wiki/Commons:Licensing#Well-known_licenses).
The main reason I wanted to upload the icons to Wikimedia is to use Metro M1, M2, M3 icons in the [Kyiv Wikivoyage guide](https://en.wikivoyage.org/wiki/Kyiv).

**Comment by alexkolodko** [comment]
@MrPaschenko Changed license to CC-BY-SA.
